---
title: "Take-Home Exercise 02"
date: "12 February 2023"
date-modified: "`r Sys.Date()`"
author: "Xinyee How"
format: html
editor: visual
execute: 
  echo: true
  eval: true
  warning: false
---

## Getting Started

### Installing packages

```{r}
pacman::p_load(tidyverse, tmap, sf, spdep, sfdep, readxl) 
```

### Importing data

**Geospatial**

```{r}
jakarta <- st_read(dsn = "data", 
                 layer="BATAS_DESA_DESEMBER_2019_DUKCAPIL_DKI_JAKARTA") %>%
  st_transform(crs = 23845)
```

**Aspatial - Vaccination rates of Jakarta from July 2021 to June 2022 (data taken from every first day of the month)**

```{r}
vac_status_july <- read_excel("data/July2021.xlsx")
```

```{r}
vac_status_july
```

```{r}
files <- c("data/July2021.xlsx","data/August2021.xlsx", "data/September2021.xlsx", "data/October2021.xlsx", "data/November2021.xlsx", "data/December2021.xlsx", "data/January2022.xlsx", "data/February2022.xlsx", "data/March2022.xlsx", "data/April2022.xlsx", "data/May2022.xlsx", "data/June2022.xlsx")
names <- c("july", "august", "september", "october", "november", "december", "january", "february", "march", "april", "may", "june")

#setNames(do.call(rbind,Map(`cbind`, 
#           lapply(files, read.table, sep=""), V4=files)), names)

#result <- list()
#for (i in seq_along(files)) {
#  result[names[i]] <- read_excel(path = files[i])
#}
```

```{r}
#setwd("C:/xinyeehow/IS415-GAA/Take-Home_Ex/Take-Home_Ex02/data")

#file_list <- list.files(pattern = "*.xlsx")
#for (i in file_list) {
#  assign(gsub(".xlsx", "", i),read_excel(i))
#}
```

```{r}
#rbindfile_list
```

```{r}
#for (i in file_list) {
 # i <- cbind(i, )
```

```{r}
#file_paths <- list.files("C:/xinyeehow/IS415-GAA/Take-Home_Ex/Take-Home_Ex02/data", pattern = ".xlsx$", full.names = TRUE)

#do.call(rbind, lapply(file_paths, function(x) 
#    transform(readxl::read_excel(x), date = sub(".xlsx$", "", basename(x)))))
```
