project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: HandsOnEx.qmd
        text: "Hands-On Exercise"
      - text: "Take-Home Exercise"
        menu:
        - text: "Take-Home Exercise 1"
          href: Take-home_Ex01.qmd
        - text: "Take-Home Exercise 2"
          href: Take-home_Ex02.qmd
        - text: "Take-Home Exercise 3"
          href: Take-home_Ex03.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

