project:
  type: website

website:
  title: "IS415-GAA"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - text: "In-Class Exercise"
        menu:
        - text: "In-Class Exercise 1"
          href: In-Class_Ex/In-Class_Ex01/In-Class_Ex01.qmd
        - text: "In-Class Exercise 2"
          href: In-Class_Ex02.qmd
        - text: "In-Class Exercise 3"
          href: In-Class_Ex03.qmd
      - text: "Hands-On Exercise"
        menu:
        - text: "Hands-On Exercise 1"
          href: Hands-On_Ex01.qmd
        - text: "Hands-On Exercise 2"
          href: Hands-On_Ex02.qmd
        - text: "Hands-On Exercise 3"
          href: Hands-On_Ex03.qmd
      - text: "Take-Home Exercise"
        menu:
        - text: "Take-Home Exercise 1"
          href: Take-home_Ex01.qmd
        - text: "Take-Home Exercise 2"
          href: Take-home_Ex02.qmd
        - text: "Take-Home Exercise 3"
          href: Take-home_Ex03.qmd

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

